// <auto-generated />
using System;
using MeetingPlanner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingPlanner.Migrations
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20181218015344_Jason")]
    partial class Jason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingPlanner.Models.Bishopric", b =>
                {
                    b.Property<int>("BishopricID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("position")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("BishopricID");

                    b.ToTable("Bishopric");
                });

            modelBuilder.Entity("MeetingPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Announcements");

                    b.Property<string>("Benediction")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("BishopricID");

                    b.Property<string>("Choirister")
                        .HasMaxLength(50);

                    b.Property<string>("CloseHymn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Conducting")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<string>("IntHymn")
                        .HasMaxLength(50);

                    b.Property<string>("Invocation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OpenHymn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Organist")
                        .HasMaxLength(50);

                    b.Property<string>("Presiding")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("SacHymn")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StakeBusiness");

                    b.Property<string>("TalkName1")
                        .HasMaxLength(50);

                    b.Property<string>("TalkName2")
                        .HasMaxLength(50);

                    b.Property<string>("TalkName3")
                        .HasMaxLength(50);

                    b.Property<string>("TalkName4")
                        .HasMaxLength(50);

                    b.Property<string>("TalkName5")
                        .HasMaxLength(50);

                    b.Property<string>("TalkSubj1")
                        .HasMaxLength(50);

                    b.Property<string>("TalkSubj2")
                        .HasMaxLength(50);

                    b.Property<string>("TalkSubj3")
                        .HasMaxLength(50);

                    b.Property<string>("TalkSubj4")
                        .HasMaxLength(50);

                    b.Property<string>("TalkSubj5")
                        .HasMaxLength(50);

                    b.Property<string>("WardBusiness");

                    b.HasKey("MeetingID");

                    b.HasIndex("BishopricID");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("MeetingPlanner.Models.Meeting", b =>
                {
                    b.HasOne("MeetingPlanner.Models.Bishopric", "Bishopric")
                        .WithMany()
                        .HasForeignKey("BishopricID");
                });
#pragma warning restore 612, 618
        }
    }
}
