// <auto-generated />
using System;
using MeetingPlanner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingPlanner.Migrations
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20181212055757_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Announcements");

                    b.Property<string>("Benediction");

                    b.Property<string>("Choirister");

                    b.Property<string>("Conducting");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Invocation");

                    b.Property<string>("Organist");

                    b.Property<string>("Presiding");

                    b.Property<string>("StakeBusiness");

                    b.Property<string>("WardBusiness");

                    b.HasKey("MeetingID");

                    b.ToTable("Meeting");
                });

            
#pragma warning restore 612, 618
        }
    }
}
